### ISSUE TITLE
moutline-move-substree-up / down with last or penultimate line

### ISSUE THREAD

**Issue by samspo** [nasfarley88/adme-el#3]
Very useful. Thanks

Can be use in addition to markdown mode because can complement  markdown-mode.el (if used as minor mode)

However, it seems there is a bug. When I use moutline-move-subtree-up or moutline-move-subtree-down with the last or penultimate line, there is an error:

> "wrong type argument: number-or-marler-p, nil"

Would also be very convenient is the cursor would stay at the same place when we use moutline-demote or mouline-promote (for the moment the cursor goes at the begining of the line

**Comment by nasfarley88** [comment]
I'll have a look at see what can be done. This code is literally copy and pasted code from outline.el and replaced `*` with `#` so I'm not sure why it is not working.

**Comment by nasfarley88** [comment]
This bug is fixed in the latest commit.

I don't use this any more so I won't be adding any new features, but feel free to fork the project and have a go yourself! `org-mode` has many enhancements which would be useful if ported over. (`org-mode` is based on outline mode.)

**Comment by samspo** [comment]
Thanks for this modification. I know and use orgmode but sometimes I prefer to write directly in markdown (would be so convinient to have the functions of orgmode but with the markdown markup).
